const actionTypes = Object.freeze({
    //app
    LANGUAGE_EN: 'LANGUAGE_EN',
    LANGUAGE_VI: 'LANGUAGE_VI',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    LOGOUT: 'LOGOUT',
    FETCH_DATA_USER: 'FETCH_DATA_USER',

    FETCH_DATA_TOP_DOCTOR: 'FETCH_DATA_TOP_DOCTOR',
    FETCH_DATA_TOP_DOCTOR_FAILED: 'FETCH_DATA_TOP_DOCTOR_FAILED'



})

export default actionTypes;