export default {
    backgroundApp: require('../picture/bgr.png'),
    logoApp: require('../picture/heart.png'),
    userImage: require('../picture/user.png'),
    iconDoctor: require('../picture/icondoctor.png'),
    iconHospital: require('../picture/Iconhospital.png'),
    schedule: require('../picture/schedule.png'),
    ambulance: require('../picture/ambulance.png'),
    consultation: require('../picture/consultation.png'),
    pharmace: require('../picture/pharmace.png'),
    doctorimage: require('../picture/doctor.png'),
    bg_main: require('../picture/bg_main.png'),
    in4: require('../picture/infor_doctor.png'),
    icon_cus: require('../picture/icon_cus.png'),
    sss: require('../picture/sss.png'),
    clinic: require('../picture/clinic.png'),
    img_bg: require('../picture/img_bg.png'),
    undo: require('../picture/undo.png'),
    eye: require('../picture/eye.png'),
    hide: require('../picture/hide.png'),
    localtion: require('../picture/localtion.png')
}